config/routes.rb
Rails.application.routes.draw do
  	get '/' => 'home#index', as: :root

	get 'signup'  => 'clients#new'
	
	post 'clients' => 'clients#create'

	get 'login' => 'sessions#new'

	post 'login' => 'sessions#create'

	delete 'logout' => 'sessions#destroy'

	get 'pending_notes' => 'notes#index'
	get 'notes/:id' => 'notes#show', as: :note
	get 'notes/:id/edit' => 'notes#edit', as: :edit_note
	patch 'notes/:id' => 'notes#update'

	get 'dashboard' => 'dashboard#index'
	post 'notes' => 'dashboard#create'

	get 'clients' => 'clients#index'

	get 'clients/:id' => 'clients#show', as: :client
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
	has_many :notes
	has_secure_password

	def admin?
		self.role == 'admin'
	end
end

app/models/note.rb
class Note < ApplicationRecord
	belongs_to :client
	has_one_attached :image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_client

	def current_client
	  @current_client ||= Client.find(session[:client_id]) if session[:client_id] 
	end

	def require_client 
  		redirect_to '/login' unless current_client 
	end

	def require_admin
		redirect_to '/' unless current_client.admin?
	end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
	before_action :require_admin, only: [:index, :show]

	def index
		@clients = Client.all
	end

	def show
		@client = Client.find(params[:id]) 
  		@notes = @client.notes
	end

	def new
		@client = Client.new
	end

	def create
		@client = Client.new(client_params)
		if @client.save 
   			session[:client_id] = @client.id 
    		redirect_to '/' 
  		else 
    		redirect_to '/signup' 
  		end 
	end

	private

	def client_params
    	params.require(:client).permit(:company, :subscription_type, :logo_img, :email, :password)
  	end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
	before_action :require_client, only: [:index, :show, :create, :note_params]

	def index
		@client = Client.find(session[:client_id])
		@notes = @client.notes


		@note = Note.new
	end

	def create
		@client = Client.find(session[:client_id])		
		@note = Client.new.notes.build(note_params)
		@note.client_id = @client.id	
		if @note.save 
   			redirect_to '/' 
  		else 
    		redirect_to '/dashboard' 
  		end 
	end

	private

	def note_params
    	params.require(:note).permit(:image)
  	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
	end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController

	before_action :require_admin

	def index
		@notes = Note.all
	end

	def show
		@note = Note.find(params[:id])
	end

	def edit
		@note = Note.find(params[:id])
	end

	def update
		@note = Note.find(params[:id])
		if @note.update_attributes(note_params) 
   			redirect_to(:action => 'show', :id => @note.id) 
  		else 
    		render 'edit' 
  		end 
	end

	private
	def note_params
		params.require(:note).permit(:employee, :doctor, :is_fraudulent, :image)
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
	end

	def create
		@client = Client.find_by_email(params[:session][:email])
		if @client && @client.authenticate(params[:session][:password])
			session[:client_id] = @client.id
		    redirect_to '/'
		else
		    redirect_to 'login'
	    end 
	end

	def destroy
		session[:client_id] = nil 
  		redirect_to '/' 
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/clients/index.html.erb
<div class = "main">
			
	<% @clients.each do |c| %>
	<div class="client">
		<div class="sec">
	    	<image><%= image_tag c.logo_img %></image>
		</div>
	    <div class="sec" id="sec-text">
		    <h3><%= c.company %></h3>
		    <p><a>Subscription: </a><%= c.subscription_type %></p>  
		    <p><%= link_to "Show Notes", client_path(c) %></p>
	    </div>
	</div>
    <% end %>

</div>

app/views/clients/new.html.erb
<div class="main">
  <div class="container">
    <h1>Sign Up</h1>
    <p>New Client Signup</p>

    <div class="signup-form">
		<%= form_for(@client) do |f| %>   
	    	<%= f.text_field :company, :placeholder => "Company" %>
	        <%= f.text_field :subscription_type, :placeholder => "Subscription Type" %>
	 		<%= f.text_field :logo_img, :placeholder => "Logo" %>
	 		<%= f.email_field :email, :placeholder => "Email" %>
	        <%= f.password_field :password, :placeholder => "Password" %> 
	    	<%= f.submit "Create an Account", class: "btn-submit" %> 
		<% end %>  
    </div>

  </div>
</div>

app/views/clients/show.html.erb
<div class = "main">
	
	<h1><%=@client.company%></h1>

	<% @notes.each do |n| %>
	<div class="note">
		<div class = "sec">
	    	<image><%= image_tag n.image %></image>
	    </div>
	    <div class="sec" id="sec-text">
	        <p><a>Employee: </a><%= n.employee %></p>
	        <p><a>Doctor: </a><%= n.doctor %></p>
	        <p><a>Fraud: </a><%= n.is_fraudulent == nil ? ("Pending") : (n.is_fraudulent) %></p>
			<p><%= link_to "See More", note_path(n) %></p>
		</div>
	</div>
	<% end %>	
	
</div>

app/views/dashboard/index.html.erb
<div class="main">
  <div class="container">
    <h1>Dashboard: <%= @client.company%></h1>

    <div class="image-upload">
    	<h3>Upload image of sick note</h3>
    	<div class="signup-form">
			<%= form_for(@note) do |f| %>
		    	<%= f.file_field :image %>	    	
		    	<%= f.submit "Load Sick Note", class: "btn-submit" %> 
			<% end %>
		</div>
    </div>

    <div class="notes-list">
    	<h3>List of Sick Notes</h3>
		<% @notes.each do |n| %>
		<div class="note">
			<div class = "sec">
		    	<image><%= image_tag n.image %></image>
		    </div>
		    <div class="sec" id="sec-text">
		    	<p><a>Client: </a><%= n.client.company %></p>
		        <p><a>Employee: </a><%= n.employee %></p>
		        <p><a>Doctor: </a><%= n.doctor %></p>
		        <p><a>Fraudulent: </a><%= n.is_fraudulent == nil ? ("Pending") : (n.is_fraudulent)%></p>     
			</div>
		</div>
		<% end %>
	</div>

  </div>
</div>

app/views/home/index.html.erb
<div class="main">
  <div class="container">
    <h1>Welcome to Sick Notes</h1>
    <p>Discover fraudulent sick notes now!</p>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SickNotes</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' =>true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  </head>

  <body>

  <div class = "nav-bar">
	 	<ul class = "nav-list">
			<li><%= link_to "Home", root_path %></li>
			<li><%= link_to "Dashboard", dashboard_path %></li>
      <% if current_client && current_client.admin? %>
			  <li><%= link_to "Pending Notes", pending_notes_path %></li>
        <li><%= link_to "Clients", clients_path %></li>
      <% end %>
		</ul> 
	</div>

  <% if current_client %> 
    <ul> 
      <li><%= current_client.email %></li> 
      <li><%= link_to "Log out", logout_path, method: "delete" %></li> 
    </ul> 
  <% else %> 
    <ul> 
      <li><%= link_to "Login", 'login' %></a></li> 
      <li><%= link_to "Signup", 'signup' %></a></li> 
    </ul> 
  <% end %>
	 		

    <%= yield %>
  </body>
</html>

app/views/notes/edit.html.erb
<div class = "main">

	<div class="edit-note">
		<image><%= image_tag @note.image %></image>

		<%= form_for(@note) do |n| %>  
	  		<div class="field"> 
	    		<%= n.label :employee %><br> 
	    		<%= n.text_field :employee %> 
	  		</div>
	  		<div class="field"> 
	    		<%= n.label :doctor %><br> 
	    		<%= n.text_field :doctor %> 
	  		</div>
	  		<div class="field"> 
	    		<%= n.label :is_fraudulent %><br> 
	    		<%= n.select(:is_fraudulent, options_for_select([[@note.is_fraudulent, @note.is_fraudulent], ['Pending', nil], ['True', true], ['False', false]]))%>
	  		</div>
	    	
	    	<%= n.submit "Save Changes", id:"edit-submit" %>
	    	
	    <% end %>
	</div>		
	
</div>

app/views/notes/index.html.erb
<div class="main">
  <div class="container">
    <h1>All pending sick notes</h1>
    <p>Below are all pending sick notes awaiting validation</p>

    <% @notes.each do |n| %>
    <% if n.is_fraudulent == nil%>
		<div class="note">
			<div class = "sec">
				<image><%= image_tag n.image %></image>
		    </div>
		    <div class="sec" id="sec-text">
		    	<p><a>Client: </a><%= n.client.company %></p>
		        <p><a>Employee: </a><%= n.employee %></p>
		        <p><a>Doctor: </a><%= n.doctor %></p>
		        <p><%= link_to "See More", note_path(n) %></p>   
			</div>
		</div>
	<% end %>
	<% end %>

  </div>
</div>

app/views/notes/show.html.erb
<div class = "main">

	<image><%= image_tag @note.image %></image>

	<p><a>Company: </a><%= @note.client.company %></p>
	<p><a>Employee: </a><%= @note.employee %></p>
	<p><a>Doctor: </a><%= @note.doctor %></p>
	<p><a>Fraud: </a><%= @note.is_fraudulent == nil ? ("Pending") : (@note.is_fraudulent) %></p>
	<p><%= link_to "Edit", edit_note_path(@note) %></p> 		
	
</div>